New grid design
googlesamples/mediapipe pull request #260
Opened 2023-10-16 14:20 UTC by AxxhimK

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

### Checklist
Please ensure the following items are complete before submitting a pull request:

- [ ] My code follows the code style of the project.
- [ ] I have updated the documentation (if applicable).
- [ ] I have added tests to cover my changes.

### Type of Change
Please check the relevant option below:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update (non-breaking change which updates documentation)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Screenshots
If applicable, please add screenshots to help explain your changes.

### Additional Notes
Add any additional information or context about the pull request here.

2023-10-16 14:39 UTC, PaulTR commented
Hi @AxxhimK. Can you please describe the reasoning behind this PR? I see the image in the top corner, but that leaves a lot of negative space in the app (the white background) that isn't being utilized. The point of the sample is to highlight the ML functionality in an easily observable way, so I want to make sure we can justify this change.

2023-10-16 14:44 UTC, PaulTR requested changes

2023-10-16 14:44 UTC, PaulTR commented on examples/interactive_segmentation/android/app/build.gradle
This shouldn't be removed. This will break the interactive segmentation sample.

2023-10-16 14:44 UTC, PaulTR commented on examples/gesture_recognizer/android/app/src/main/res/drawable/ge_logo.jpg
Is this PR related to a school project?

https://corporatedesign.htw-berlin.de/logos/piktogramme-studiengaenge/

I'm guessing this isn't something relevant to this repo and shouldn't have been submitted here. Maybe you cloned this repo for a class project to edit and set up your git for the wrong upstream? :)

2023-10-16 14:44 UTC, PaulTR commented on examples/gesture_recognizer/android/app/src/main/assets/gesture_recognizer.task
We don't store models in the repo due to size and wanting the ability to update them at runtime for newer models. This would need to be removed.

2023-10-16 14:44 UTC, PaulTR commented on examples/gesture_recognizer/android/app/src/main/java/com/google/mediapipe/examples/gesturerecognizer/OverlayView.kt
> -/*
Copyright message here shouldn't be removed from the repo.

2023-10-16 14:44 UTC, PaulTR commented on examples/gesture_recognizer/android/app/src/main/res/values/colors.xml
> +    <color name="htwGrey">#AFAFAF</color>
Another reason I'm guessing you're using this for a school project - changing the branding :)

2023-10-16 14:45 UTC, AxxhimK commented
Hey Paul,

I'm really sorry for the inconvenience but I started a pull request by accident. I'm very lost on GitHub right now and actually trying to use Google MediaPipe exclusively for a project in my bachelor thesis and not public. You can ignore this pull request and past changes from me. 

Kind regards

Achim

> Am 16.10.2023 um 16:40 schrieb Paul Ruiz ***@***.***>:
> 
> 
> Hi @AxxhimK <https://github.com/AxxhimK>. Can you please describe the reasoning behind this PR? I see the image in the top corner, but that leaves a lot of negative space in the app (the white background) that isn't being utilized. The point of the sample is to highlight the ML functionality in an easily observable way, so I want to make sure we can justify this change.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/googlesamples/mediapipe/pull/260#issuecomment-1764628446>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ARCIJHWJT5SYF6QFXVYWUULX7VBMVAVCNFSM6AAAAAA6CI7GZCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONRUGYZDQNBUGY>.
> You are receiving this because you were mentioned.
>

2023-10-16 14:47 UTC, PaulTR commented
Yeah looking over your original project and this being a 'bachelor thesis', I'm guessing this was a mistake :) Please resubmit if that is incorrect.

2023-10-16 14:47 UTC, closed without merging

2023-10-16 14:48 UTC, PaulTR commented
No problem, good luck with your courses!

2023-10-30 10:58 UTC, AxxhimK commented
> No problem, good luck with your courses!

Thank you, I actually have a rather basic question if you have the time @PaulTR 

Let's say I want to implement a button click whenever a gesture is recognized. For example, "click next" when the Thumb_Up gesture is recognized. Where do I call the gesture from? Do I call it from categories or is it easier to just use it the actual gesture results from the GestureRecognizerHelper class? 

The code is hard for me to understand because of the complexity. Maybe you can give me a hint where I can get direct access to the gestures.

Thanks in advance,

Achim