iOS pose landmarker tasks vision example
googlesamples/mediapipe pull request #347
Opened 2024-03-19 02:54 UTC by st-tuanmai

### Description
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

### Checklist
Please ensure the following items are complete before submitting a pull request:

- [x] My code follows the code style of the project.
- [ ] I have updated the documentation (if applicable).
- [x] I have added tests to cover my changes.

### Type of Change
Please check the relevant option below:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation update (non-breaking change which updates documentation)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### Screenshots
![IMG_1319](https://github.com/googlesamples/mediapipe/assets/62716934/638fcd84-69cf-45e3-b923-0a8c160b43c7)
![IMG_1320](https://github.com/googlesamples/mediapipe/assets/62716934/f4f14563-d9c6-4ef6-8606-5e479ccf409a)

### Additional Notes
Add any additional information or context about the pull request here.

2024-03-19 09:47 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarker/Services/CameraFeedService.swift
> +      if reason == .videoDeviceInUseByAnotherClient {
Convert this to a switch case

2024-03-19 09:51 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarker/Services/CameraFeedService.swift
> +      let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer)!
All of this seems to be unused since we are passing the sample buffer with the device orientation for the calculations. Can you remove this?

2024-03-19 09:54 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarker/Services/PoseLandmarkerService.swift
> +    print(image.imageOrientation.rawValue)
Remove print

2024-03-19 09:55 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarker/Services/PoseLandmarkerService.swift
> +          //        CMTime(seconds: Double(timestampMs) / 1000, preferredTimescale: 1000)
Remove commented code if unused

2024-03-19 10:00 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarker/Services/CameraFeedService.swift
> +      let imageBuffer = CMSampleBufferGetImageBuffer(sampleBuffer)!
Please disregard this comment. I got confused. This is correct. Can you replace the force unwrap with a guard condition?

2024-03-19 10:04 UTC, priankakariatyml commented on examples/pose_landmarker/ios/RunScripts/download_models.sh
> +fi
add a new line after `fi`

2024-03-20 09:54 UTC, priankakariatyml requested changes
@st-tuanmai  Can we also add a drop down for switching between gpu and cpu delegates in the bottom sheet. All iOS tasks have this capability now.

2024-03-22 13:37 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarkerTests/PoseLandmarkerTests.swift
> +  func assertLandmarkAreEqual(
s/LandmarkAre/LandmarksAre

2024-03-22 13:43 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarker/ViewContoller/BottomSheetViewController.swift
> +  @IBOutlet weak var choseModelButton: UIButton!
s/choseModelButton/chooseModelButton

2024-03-22 13:43 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarker/ViewContoller/BottomSheetViewController.swift
> +  @IBOutlet weak var delegateButton: UIButton!
s/delegateButton/chooseDelegateButton

2024-03-22 13:51 UTC, priankakariatyml commented on examples/pose_landmarker/ios/PoseLandmarker/ViewContoller/BottomSheetViewController.swift
> +        title: delegate == .CPU ? "CPU" : "GPU",
Define an enum for delegate similar to `Model` for model selection.

2024-03-25 16:53 UTC, priankakariatyml approved these changes

2024-03-25 18:39 UTC, PaulTR commented on examples/pose_landmarker/ios/PoseLandmarker/pose_landmarker_full.task
Please remove the models from the repo. The download script will handle that.

2024-03-25 18:57 UTC, PaulTR commented
Can we set this to use the back camera instead of the front? For face and hands front isn't too bad since the devs can test against themselves, but for pose it's a lot more useful to see a full person

2024-03-26 17:51 UTC, PaulTR commented
Thanks. Last thing is it looks like the connection from the right knee to the right hip is missing.

2024-03-27 07:20 UTC, st-tuanmai commented
@PaulTR when I check on `PoseLandmarker.poseLandmarks` (PoseLandmarker connections)
I didn't find the connection between points 24 and 26 (right knee and right hip), 25 and 27(left foot and left knee). please ask mediapipe core team to check again.

2024-03-28 16:14 UTC, PaulTR commented
Alright that PR just went in so we'll just need to update later.

2024-03-28 16:14 UTC, merged

2024-04-12 15:00 UTC, diyoraharshitN commented
Hi @PaulTR @st-tuanmai @priankakariatyml @tjohns @markmcd 

i have searched in the example but didn't find any seperetion for Left Body landmarks and Right Body landmarks points.
where in web version in the node_modules @mediapipe>holistic>index.d.ts there is const declared for Left side landmark for pose as POSE_LANDMARKS_LEFT and for Right side landmark for pose as POSE_LANDMARKS_RIGHT.

is there any way to separate Left and Right landmarks from the MPPNormalizedLandmark array that we get as result array from the scan?

Thank you
Harshit

2024-04-12 16:30 UTC, PaulTR commented
Hi Harshit,

Please post the question on the GitHub issues tab for tracking rather than on a closed out pull request :)

Thanks

2024-04-12 17:22 UTC, diyoraharshitN commented
Hi @PaulTR 

Thanks for the update

i have already posted same on the issue.

https://github.com/google/mediapipe/issues/4895#issuecomment-2051796753

2024-04-12 17:35 UTC, PaulTR commented
Then we probably don't need to tag everyone (many of whom aren't related to
the issue) in a closed ticket from a separate repo ;) feel free to post as
an issue in this repo though.

On Fri, Apr 12, 2024, 11:22 AM diyoraharshitN ***@***.***>
wrote:

> Hi @PaulTR <https://github.com/PaulTR>
>
> Thanks for the update
>
> i have already posted same on the issue.
>
> google/mediapipe#4895 (comment)
> <https://github.com/google/mediapipe/issues/4895#issuecomment-2051796753>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/googlesamples/mediapipe/pull/347#issuecomment-2052174796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAR2C37B6ENYJCOXIS6WLF3Y5AJ7BAVCNFSM6AAAAABE4W7Y5CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDANJSGE3TINZZGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-04-29 14:00 UTC, mohapatraswagatika-firebase commented
Hi @PaulTR  @st-tuanmai 
[IMG_0816](https://github.com/googlesamples/mediapipe/assets/108865488/59c74884-9efe-4cf8-9124-6a9ccc672b4c)

I'm encountering an issue with the PoseLandmarker model where certain connections between key points are missing in the output. Specifically, the connections between points 24 and 26 (right knee and right hip) and 25 and 27 (left foot and left knee) are consistently not detected.
Which solution will work from below - 
Making changes in the code or model to improve key point detection and connection.
Considering the use of TensorFlow Lite models as an alternative solution.
I'm seeking advice from the community to determine the best course of action.

Any insights, suggestions, or recommendations would be greatly appreciated. Thank you!

2024-04-29 16:17 UTC, PaulTR commented
This fix is also added recently, just waiting on a new dependency to be pushed out :)

2024-04-29 16:29 UTC, st-tuanmai commented
<img width="939" alt="Screenshot 2024-04-29 at 23 19 30" src="https://github.com/googlesamples/mediapipe/assets/62716934/7ab28328-aec7-44d6-a028-bf91a16cf803">
I checked the source code of mediapipe and saw that there were those 2 connections in the MPPPoseLandmarksConnections definition.
However, it is not available on iOS MediaPipeTasksVision 0.10.12

2024-04-30 05:28 UTC, mohapatraswagatika-firebase commented
> Hi @mohapatraswagatika-firebase @PaulTR I think adding the connection between the right knee and right hip (24-26) and the connection between the left leg and left knee (25-27) can solve this case the fastest way before waiting for the mediapipe team update `PoseLandmarker.poseLandmarks`
> 
> code like:
> 
> ```
>     var poseLandmarks: [Connection] = [
>       Connection(start: 24, end: 26),
>       Connection(start: 25, end: 27)
>     ]
>       poseLandmarks.append(contentsOf: PoseLandmarker.poseLandmarks)`
> ```

@st-tuanmai  can you please tell me on which page and where to add these lines

2024-04-30 06:21 UTC, mohapatraswagatika-firebase commented
> poseLandmarks

when it will be available on live

2024-04-30 07:57 UTC, st-tuanmai commented
@mohapatraswagatika-firebase

2024-04-30 08:00 UTC, st-tuanmai commented
@mohapatraswagatika-firebase 
`// Right knee and right hip(24-26)

        // Left foot and left knee(25-27)
        var poseLandmarks: [Connection] = [
          Connection(start: 24, end: 26),
          Connection(start: 25, end: 27)
        ]
          poseLandmarks.append(contentsOf: PoseLandmarker.poseLandmarks)
          let lines: [Line] = poseLandmarks
            .map({ connection in
              let start = dots[Int(connection.start)]
              let end = dots[Int(connection.end)]
              return Line(from: start,
                          to: end)
            })`

2024-04-30 08:13 UTC, mohapatraswagatika-firebase commented
@st-tuanmai  Thank you so much for your solution . I got my result . if i want to remove  some connection how can i do that .

> @mohapatraswagatika-firebase `// Right knee and right hip(24-26)
> 
> ```
>     // Left foot and left knee(25-27)
>     var poseLandmarks: [Connection] = [
>       Connection(start: 24, end: 26),
>       Connection(start: 25, end: 27)
>     ]
>       poseLandmarks.append(contentsOf: PoseLandmarker.poseLandmarks)
>       let lines: [Line] = poseLandmarks
>         .map({ connection in
>           let start = dots[Int(connection.start)]
>           let end = dots[Int(connection.end)]
>           return Line(from: start,
>                       to: end)
>         })`
> ```

2024-04-30 08:33 UTC, st-tuanmai commented
You can define the connections you want without using PoseLandmarker.poseLandmarks.
var poseLandmarks: [Connection] = [
      Connection(start: 24, end: 26),
      Connection(start: 25, end: 27)
    ]
let lines: [Line] = poseLandmarks
        .map({ connection in
          let start = dots[Int(connection.start)]
          let end = dots[Int(connection.end)]
          return Line(from: start,
                      to: end)
        })

2024-04-30 08:40 UTC, mohapatraswagatika-firebase commented
@st-tuanmai  my question is if i want to remove face pose overlays  how will i do it 

> You can define the connections you want without using PoseLandmarker.poseLandmarks. var poseLandmarks: [Connection] = [ Connection(start: 24, end: 26), Connection(start: 25, end: 27) ] let lines: [Line] = poseLandmarks .map({ connection in let start = dots[Int(connection.start)] let end = dots[Int(connection.end)] return Line(from: start, to: end) })

@st-tuanmai  my question is if i want to remove face pose overlays  how will i do it

2024-05-01 05:33 UTC, mohapatraswagatika-firebase commented
> You can define the connections you want without using PoseLandmarker.poseLandmarks. var poseLandmarks: [Connection] = [ Connection(start: 24, end: 26), Connection(start: 25, end: 27) ] let lines: [Line] = poseLandmarks .map({ connection in let start = dots[Int(connection.start)] let end = dots[Int(connection.end)] return Line(from: start, to: end) })

@st-tuanmai  This above solution is for only line removal . if we want to remove both dot and line , only display 12 connection then how can we to achieve this . Also if i want to check the visibility result from detection how can i achieve this.

2024-05-03 02:24 UTC, st-tuanmai commented
@mohapatraswagatika-firebase 
You can remove the dots after removing the connections.


        var poseLandmarks: [Connection] = [
          Connection(start: 24, end: 26),
          Connection(start: 25, end: 27)
        ]
          poseLandmarks.append(contentsOf: PoseLandmarker.poseLandmarks)
        poseLandmarks.removeAll(where: {$0.start <= 10})
          let lines: [Line] = poseLandmarks
            .map({ connection in
              let start = dots[Int(connection.start)]
              let end = dots[Int(connection.end)]
              return Line(from: start,
                          to: end)
            })
        dots.remove(atOffsets: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

2024-05-03 02:26 UTC, st-tuanmai commented
@mohapatraswagatika-firebase 
The model output has the NormalizedLandmark data type.
You can refer to PoseLandmarkerTests.swift

2024-05-03 04:40 UTC, mohapatraswagatika-firebase commented
@st-tuanmai  Thank you, I understand your point. However, the issue remains: it only returns x, y, z, visibility, and presence values. How can we determine which pose or point these results correspond to?

> @mohapatraswagatika-firebase The model output has the NormalizedLandmark data type. You can refer to PoseLandmarkerTests.swift

2024-05-03 09:07 UTC, st-tuanmai commented
@mohapatraswagatika-firebase pose landmarks define with index:
0 - nose
1 - left eye (inner)
2 - left eye
3 - left eye (outer)
4 - right eye (inner)
5 - right eye
6 - right eye (outer)
7 - left ear
8 - right ear
9 - mouth (left)
10 - mouth (right)
11 - left shoulder
12 - right shoulder
13 - left elbow
14 - right elbow
15 - left wrist
16 - right wrist
17 - left pinky
18 - right pinky
19 - left index
20 - right index
21 - left thumb
22 - right thumb
23 - left hip
24 - right hip
25 - left knee
26 - right knee
27 - left ankle
28 - right ankle
29 - left heel
30 - right heel
31 - left foot index
32 - right foot index

2025-03-28 08:46 UTC, diyoraharshitN commented
@st-tuanmai is dynamic orientation supported in mediapipe pose landmark for iOS?
i have run this example in iPad and changing orientation while running app lines are not properly align to body.
can you please guide me on this.